# Usa una imagen base de Python oficial. Reemplaza la versión según sea necesario.
FROM python:3.11-slim

# Establece la variable de entorno para evitar que Python escriba archivos .pyc en el disco
# y para que la salida estándar y de error no se almacene en búfer.
ENV PYTHONUNBUFFERED 1

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el archivo de requisitos y las instala primero.
# Esto aprovecha el caché de Docker si los requisitos no cambian.
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de la aplicación.
COPY . .

# Copia el entrypoint que aplica migraciones, crea superusuario y popula datos
COPY entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# Establece el comando predeterminado para correr el servidor de desarrollo.
# (Esto se puede sobrescribir fácilmente en docker-compose.yml)
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]