# Generated by Django 5.2.6 on 2025-10-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('comuna_vive', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna de Residencia')),
                ('tipo_cliente', models.CharField(choices=[('B2C', 'Persona Natural'), ('B2B', 'Empresa/Institución')], default='B2C', max_length=3, verbose_name='Tipo de Cliente')),
                ('intereses', models.TextField(blank=True, verbose_name='Intereses (Ej: Resina, Encuadernación)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones de Gestión (Seguimiento, etc.)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Taller')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('fecha_taller', models.DateField(verbose_name='Fecha del Taller')),
                ('hora_taller', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online')], default='PRESENCIAL', max_length=15, verbose_name='Modalidad')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio (CLP)')),
                ('cupos_totales', models.IntegerField(default=10, verbose_name='Cupos Máximos')),
                ('cupos_disponibles', models.IntegerField(default=0, editable=False, verbose_name='Cupos Disponibles')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='¿Está activo/visible?')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monto Pagado')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pago Pendiente'), ('PAGADO', 'Pagado Completo'), ('ABONADO', 'Abonado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10, verbose_name='Estado de Pago')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='crm.cliente')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='crm.taller')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('cliente', 'taller')},
            },
        ),
    ]
