# Generated by Django 5.2.7 on 2025-10-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Interés')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o Palabras Clave')),
            ],
            options={
                'verbose_name_plural': 'Intereses',
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='intereses',
        ),
        migrations.AddField(
            model_name='taller',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='talleres/', verbose_name='Imagen del Taller'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='intereses_cliente',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='crm.interes', verbose_name='Intereses del Cliente'),
        ),
    ]
