# Generated by Django 5.2.7 on 2025-10-12 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_interes_remove_cliente_intereses_taller_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres', to='crm.interes', verbose_name='Categoría del Taller'),
        ),
    ]
