# Generated by Django 5.2.7 on 2025-10-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_taller_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
