# Generated by Django 5.2.7 on 2025-10-13 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Producto/Kit')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_venta', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio de Venta (CLP)')),
                ('esta_disponible', models.BooleanField(default=True, verbose_name='¿Está disponible para la venta?')),
            ],
            options={
                'verbose_name_plural': 'Productos (Kits)',
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto Total Pagado')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pago Pendiente'), ('PAGADO', 'Pagado Completo'), ('ANULADO', 'Anulado')], default='PAGADO', max_length=10, verbose_name='Estado de Pago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_kits', to='crm.cliente')),
            ],
            options={
                'verbose_name_plural': 'Ventas de Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio al Vender')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='crm.ventaproducto')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
