# Generated by Django 5.2.7 on 2025-10-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_producto_ventaproducto_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
