# Generated by Django 5.2.7 on 2025-10-24 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_producto_stock_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, unique=True, verbose_name='Razón Social')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono_empresa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Empresa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa (B2B)',
                'verbose_name_plural': 'Empresas (B2B)',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico (Contacto)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento (si aplica)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='intereses_cliente',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='crm.interes', verbose_name='Intereses del Contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo (Contacto)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono (Contacto)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('B2C', 'Persona Natural'), ('B2B', 'Contacto Empresa')], default='B2C', max_length=3, verbose_name='Tipo de Contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='crm.empresa', verbose_name='Empresa (si aplica)'),
        ),
    ]
